#include <chrono>
#include <iostream>
#include <mutex>
#include <optional>
#include <queue>
#include <semaphore>
#include <thread>

struct Job {
  int id;
  int count;
};

// Unbounded queue with enqueue and non-waiting dequeue
class JobQueue {
  std::queue<Job> jobs;
  std::mutex mut;

public:
  // The autogenerated default constructor already calls the default
  // constructor on all its members so we don't need to write our own.
  //JobQueue() : jobs{} {}

  // TODO: Make this thread-safe
  void enqueue(Job job) {
    std::unique_lock lk{mut};
    jobs.push(job);
  }

  // TODO: Make this thread-safe
  std::optional<Job> try_dequeue() {
    std::unique_lock lk{mut};
    if (jobs.empty()) {
      return std::nullopt;
    } else {
      Job job = jobs.front();
      jobs.pop();
      return job;
    }
  }
};

int main() {
  JobQueue queue;

  std::thread t1{[&queue]() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    queue.enqueue(Job{420, 420});
  }};
  std::thread t2{[&queue]() {
    std::this_thread::sleep_for(std::chrono::seconds(2));
    std::optional<Job> job = queue.try_dequeue();
    if (job) {
        std::cout << "This should print 420: " << job->id << std::endl;
    } else {
        std::cout << "Did not get a job" << std::endl;
    }
  }};

  t1.join();
  t2.join();

  return 0;
}
